category/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "category"
urlpatterns = [
    path("categoryadd/", views.CategoryAdd.as_view(), name="categoryadd"),
    path("categoryread/", views.CategoryView.as_view(), name="categoryread"),
]

product/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "product"
urlpatterns = [
    path("productadd/", views.ProductAdd.as_view(), name="productadd"),
    path("productread/", views.ProductView.as_view(), name="productread"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("", views.UserAdd.as_view(), name="useradd"),
    path("userread/", views.UserView.as_view(), name="userread"),
]

userCRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
]

category/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)
    vendor = models.CharField(max_length=10)

    def __str__(self):
        return self.name

product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.CharField(max_length=10)
    stock = models.IntegerField(max_length=30)
    price = models.FloatField(max_length=100)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.name

user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=10)
    email = models.CharField(max_length=30)
    password = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.name

category/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import Category

# Create your views here.
class CategoryAdd(TemplateView):
    template_name = "categoryadd.html"

    def post(self, request):
        category = Category()
        category.name = request.POST.get("name")
        category.vendor = request.POST.get("vendor")
        category.save()

        return render(
            request,
            "categoryadd.html",
        )


class CategoryView(TemplateView):
    template_name = "categoryread.html"

    def get(self, request):

        category = Category.objects.all()
        return render(request, self.template_name, {"category": category})

product/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import Product

# Create your views here.
class ProductAdd(TemplateView):
    template_name = "productadd.html"

    def post(self, request):
        product = Product()
        product.name = request.POST.get("name")
        product.quantity = request.POST.get("quantity")
        product.stock = request.POST.get("stock")
        product.price = request.POST.get("price")
        product.image = request.POST.get("image")
        product.save()

        return render(
            request,
            "productadd.html",
        )


class ProductView(TemplateView):
    template_name = "productread.html"

    def get(self, request):

        product = Product.objects.all()
        return render(request, self.template_name, {"product": product})

user/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import User
from django.http.response import HttpResponse

# Create your views here.
class UserAdd(TemplateView):
    template_name = "useradd.html"

    def post(self, request):
        user = User()
        user.name = request.POST.get("name")
        user.email = request.POST.get("email")
        user.address = request.POST.get("address")
        user.password = request.POST.get("password")
        user.image = request.POST.get("image")
        user.save()

        return HttpResponse("thank you for your Registration")


class UserView(TemplateView):
    template_name = "userread.html"

    def get(self, request):

        user = User.objects.all()
        return render(request, self.template_name, {"user": user})

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>User Add/Read</title>
    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    {% block csspart %}
    <link
      rel="stylesheet"
      href="{%static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
    <!-- overlayScrollbars -->
    <link
      rel="stylesheet"
      href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
    />
    {% endblock csspart %}
  </head>

  {% block bodytag %}
  {% endblock bodytag%} 

  {% block nav%}
    <div class="wrapper">
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"
              ><i class="fas fa-bars"></i
            ></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
          </li>
        </ul>
      </nav>
      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
          <img
            src="{%static 'dist/img/AdminLTELogo.png' %}"
            alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3"
            style="opacity: 0.8"
          />
          <span class="brand-text font-weight-light">AdminLTE 3</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar user panel (optional) -->
          <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
              <img
                src="{%static 'dist/img/traveler1.jpg' %}"
                class="img-circle elevation-2"
                alt="User Image"
              />
            </div>
            <div class="info">
              <a href="#" class="d-block">Anupam Siwakoti</a>
            </div>
          </div>

          <!-- SidebarSearch Form -->
          <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
              <input
                class="form-control form-control-sidebar"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <div class="input-group-append">
                <button class="btn btn-sidebar">
                  <i class="fas fa-search fa-fw"></i>
                </button>
              </div>
            </div>
          </div>

          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul
              class="nav nav-pills nav-sidebar flex-column"
              data-widget="treeview"
              role="menu"
              data-accordion="false"
            >
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-users"></i>
                  <p>
                    USER
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'user:useradd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add User</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'user:userread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View User</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon far fa-arrow-alt-circle-right"></i>
                  <p>
                    Product
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'product:productadd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add Product</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'product:productread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View Product</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-edit"></i>
                  <p>
                    Category
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'category:categoryadd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add Category</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'category:categoryread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View Category</p>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>
      {% endblock nav%}
      
      {% block bodycontent%} 
      {% endblock bodycontent%}

      {% block redirect%}
      {% endblock redirect%}
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <strong
          >Copyright &copy; 2014-2021
          <a href="https://adminlte.io">AdminLTE.io</a>.</strong
        >
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
          <b>Version</b> 3.1.0
        </div>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    {% block addjquery %}
    <!-- jQuery -->
    <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{%static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge("uibutton", $.ui.button);
    </script>
    <!-- Bootstrap 4 -->
    <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{%static 'dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{%static 'dist/js/demo.js' %}"></script>
    <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
    {% endblock addjquery %}
  </body>
</html>

templates/categoryadd.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
    <link
      rel="stylesheet"
      href="{%static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>General Form</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">General Form</li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title">Add Category</h3>
                  </div>
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form method="post" action="{% url 'category:categoryadd' %}">
                   {% csrf_token %}
                    <div class="card-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Category Name</label>
                        <input
                          type="text"
                          class="form-control"
                          name="name"
                          id="exampleInputEmail1"
                          placeholder="category name"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Vendor</label>
                        <input
                          type="text"
                          class="form-control"
                          name="vendor"
                          id="exampleInputEmail1"
                          placeholder="Vendor name"
                        />
                      </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">
                        Add Category
                      </button>
                    </div>
                  </form>
                </div>
                <!-- /.card -->
              </div>
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
        <!-- jQuery -->
        <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
        <!-- Bootstrap 4 -->
        <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- bs-custom-file-input -->
        <script src="{%static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{%static 'dist/js/adminlte.min.js' %}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{%static 'dist/js/demo.js' %}"></script>
        <!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
        <script>
          $(function () {
            bsCustomFileInput.init();
          });
        </script>
    {% endblock addjquery %}
  </body>
</html>

templates/productadd.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
    <link
      rel="stylesheet"
      href="{%static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>General Form</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">General Form</li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title">Add Product</h3>
                  </div>
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form method="post" action="{% url 'product:productadd' %}">
                  {% csrf_token %}
                    <div class="card-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Product Name</label>
                        <input
                          type="name"
                          class="form-control"
                          name="name"
                          id="exampleInputEmail1"
                          placeholder="Product name"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Product Quantity</label>
                        <input
                          type="number"
                          class="form-control"
                          name="quantity"
                          id="exampleInputEmail1"
                          placeholder="Product quantity"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Stock</label>
                        <input
                          type="number"
                          class="form-control"
                          name="stock"
                          id="exampleInputEmail1"
                          placeholder="Stock"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Price</label>
                        <input
                          type="number"
                          class="form-control"
                          name="price"
                          id="exampleInputPassword1"
                          placeholder="Password"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputFile">Image</label>
                        <div class="input-group">
                          <div class="custom-file">
                            <input
                              type="file"
                              class="custom-file-input"
                              name="image"
                              id="exampleInputFile"
                            />
                            <label
                              class="custom-file-label"
                              for="exampleInputFile"
                              >Choose file</label
                            >
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">
                        Add Product
                      </button>
                    </div>
                  </form>
                </div>
                <!-- /.card -->
              </div>
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
        <!-- jQuery -->
        <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
        <!-- Bootstrap 4 -->
        <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- bs-custom-file-input -->
        <script src="{%static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{%static 'dist/js/adminlte.min.js' %}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{%static 'dist/js/demo.js' %}"></script>
        <!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
        <script>
          $(function () {
            bsCustomFileInput.init();
          });
        </script>
    {% endblock addjquery %}
  </body>
</html>

templates/useradd.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
    <link
      rel="stylesheet"
      href="{%static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>General Form</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">General Form</li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- Main content -->
        <section class="content">
          <div class="container-fluid">
            <div class="row">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                  <div class="card-header">
                    <h3 class="card-title">Register User</h3>
                  </div>
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form method="post" action="{% url 'user:useradd' %}">
                  {% csrf_token %}
                    <div class="card-body">
                      <div class="form-group">
                        <label for="exampleInputEmail1">Name</label>
                        <input
                          type="text"
                          class="form-control"
                          name="name"
                          id="exampleInputEmail1"
                          placeholder="Enter Name"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Address</label>
                        <input
                          type="text"
                          class="form-control"
                          name="address"
                          id="exampleInputEmail1"
                          placeholder="Enter Address"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input
                          type="email"
                          class="form-control"
                          name="email"
                          id="exampleInputEmail1"
                          placeholder="Enter email"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input
                          type="password"
                          class="form-control"
                          name="password"
                          id="exampleInputPassword1"
                          placeholder="Password"
                        />
                      </div>
                      <div class="form-group">
                        <label for="exampleInputFile">Image</label>
                        <div class="input-group">
                          <div class="custom-file">
                            <input
                              type="file"
                              class="custom-file-input"
                              name="image"
                              id="exampleInputFile"
                            />
                            <label
                              class="custom-file-label"
                              for="exampleInputFile"
                              >Choose file</label
                            >
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                      <button type="submit" class="btn btn-primary">
                        Register
                      </button>
                    </div>
                  </form>
                </div>
                <!-- /.card -->
              </div>
            </div>
            <!-- /.row -->
          </div>
          <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
        <!-- jQuery -->
        <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
        <!-- Bootstrap 4 -->
        <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <!-- bs-custom-file-input -->
        <script src="{%static 'plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
        <!-- AdminLTE App -->
        <script src="{%static 'dist/js/adminlte.min.js' %}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{%static 'dist/js/demo.js' %}"></script>
        <!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
        <script>
          $(function () {
            bsCustomFileInput.init();
          });
        </script>
    {% endblock addjquery %}
  </body>
</html>